export const APP_ACTIONS = {
  CLEAR_CURRENT: "APP/CLEAR_CURRENT",
  SET_LIST: "APP/SET_LIST",
  CUD_LIST: "APP/CUD_LIST",
  SET_CURRENT: "APP/SET_CURRENT",
  CUD_CURRENT: "APP/CUD_CURRENT",
  CLEAR_LIST: "APP/CLEAR_LIST",
};

export const RECOMMEND_ACTIONS = {
  CLEAR_CURRENT: "RECOMMEND/CLEAR_CURRENT",
  SET_LIST: "RECOMMEND/SET_LIST",
  CUD_LIST: "RECOMMEND/CUD_LIST",
  SET_CURRENT: "RECOMMEND/SET_CURRENT",
  CUD_CURRENT: "RECOMMEND/CUD_CURRENT",
  CLEAR_LIST: "RECOMMEND/CLEAR_LIST",
};
